FROM rockylinux:9
RUN dnf -y --enablerepo=devel install make automake autoconf libtool libsodium-devel mariadb-devel
WORKDIR /code
COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]