FROM rockylinux:9
RUN dnf -y --enablerepo=devel install make automake autoconf libtool mariadb-devel epel-release
RUN dnf -y --enablerepo=devel install libsodium-devel
WORKDIR /code
COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]