// Before publishing your new repository:
// 1. Write the readme file
// 2. Update the issues link in Contributing section in the readme file
// 3. Update the discussion link in config.yml file in .github/ISSUE_TEMPLATE directory

= MRP_01: MariaDB Ristretto255 Plugin

This package provides all the functionalities of libsodium ristretto255 methods in the form of user-defined functions (UDFs) for MySQL.

== Installation

WIP

== Functions

=== Encoded element validation
==== `ristrettoisvalidpoint`

The function checks that the input argument `p` is a valid ristretto255-encoded element. Returns 1 on success, 0 if the check didn't pass.

=== Random group element
==== `ristrettorandom`

Returns a random ristretto255 group element.

=== Hash-to-group
==== `ristrettofromhash`

The function maps a 64 bytes vector to a ristretto255 group element and returns it.

=== Scalar multiplication
==== `scalarmultristretto`


==== `scalarmultristrettobase`

=== Element addition/subtraction
==== `ristrettoadd`

==== `ristrettosub`

=== Scalar arithmetic over L
==== `ristrettoscalarrandom`

==== `ristrettoscalarreduce`

==== `ristrettoscalarinvert`

==== `ristrettoscalarnegate`

==== `ristrettoscalarcomplement`

==== `ristrettoscalaradd`

==== `ristrettoscalarsub`

==== `ristrettoscalarmul`

== Development

Compiling this project requires at least the following packages to be installed:

- `make`
- `automake`
- `autoconf`
- `libtool`
- `mariadb-devel`
- `libsodium-devel`

To install, run the following commands in project root directory:
[source,shell]
----
autoreconf -fvi

./configure
make
sudo make install
sudo make installdb
----
And to uninstall, run the following commands:
[source,shell]
----
make uninstalldb
make uninstall
----

== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/repo-template/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
