// Before publishing your new repository:
// 1. Write the readme file
// 2. Update the issues link in Contributing section in the readme file
// 3. Update the discussion link in config.yml file in .github/ISSUE_TEMPLATE directory

= MRP_01: MariaDB Ristretto255 Plugin

This package provides all the functionalities of libsodium ristretto255 methods in the form of user-defined functions (UDFs) for MySQL.

== Installation

Install the mrp_01 package:

[source,shell]
----
yum install mrp_01.rpm
----

Install the user defined functions via the included SQL script:

[source,shell]
----
mariadb < /opt/teragrep/mrp_01/share/install_ristretto.sql
----

Or alternatively, install the user defined functions manually via queries:

[source,sql]
----
USE mysql;

DROP FUNCTION IF EXISTS ristrettoisvalidpoint;
CREATE FUNCTION ristrettoisvalidpoint RETURNS INTEGER SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettorandom;
CREATE FUNCTION ristrettorandom RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettofromhash;
CREATE FUNCTION ristrettofromhash RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS scalarmultristretto;
CREATE FUNCTION scalarmultristretto RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS scalarmultristrettobase;
CREATE FUNCTION scalarmultristrettobase RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoadd;
CREATE FUNCTION ristrettoadd RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettosub;
CREATE FUNCTION ristrettosub RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalarrandom;
CREATE FUNCTION ristrettoscalarrandom RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalarreduce;
CREATE FUNCTION ristrettoscalarreduce RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalarinvert;
CREATE FUNCTION ristrettoscalarinvert RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalarnegate;
CREATE FUNCTION ristrettoscalarnegate RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalarcomplement;
CREATE FUNCTION ristrettoscalarcomplement RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalaradd;
CREATE FUNCTION ristrettoscalaradd RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalarsub;
CREATE FUNCTION ristrettoscalarsub RETURNS STRING SONAME 'lib_sodium_ristretto.so';
DROP FUNCTION IF EXISTS ristrettoscalarmul;
CREATE FUNCTION ristrettoscalarmul RETURNS STRING SONAME 'lib_sodium_ristretto.so';
----

== SQL Functions

=== Encoded element validation

`ristrettoisvalidpoint(BINARY(32) p)`

The function checks that the input argument `p` is a valid ristretto255-encoded element. Returns 1 on success, 0 if the check didn't pass.

=== Random group element

`ristrettorandom()`

The function returns a random ristretto255 group element in binary string format.

=== Hash-to-group

`ristrettofromhash(BINARY(64) a)`

The function maps a 64 bytes vector that given as input argument `a` to a ristretto255 group element and returns it.

=== Scalar multiplication

`scalarmultristretto(BINARY(32) a, BINARY(32) b);`

The function multiplies an ristretto element `b` by a scalar `a` and returns the resulting element.

`scalarmultristrettobase(BINARY(32) a);`

The function multiplies the randomly generated ristretto element by a scalar `a` and returns the resulting element.

=== Element addition and subtraction

`ristrettoadd(BINARY(32) a, BINARY(32) b)`

The function adds the ristretto element `a` to ristretto element `b` and returns the resulting element.

`ristrettosub(BINARY(32) a, BINARY(32) b)`

The function subtracts the ristretto element `a` to the ristretto element `b` and returns the resulting element.

=== Scalar arithmetic over L

The ristrettoscalar*() function set operates over scalars in the `[0..L[` interval, `L` being the order of the ristretto255 group: (2^252 + 27742317777372353535851937790883648493).

`ristrettoscalarrandom()`

The function returns a random scalar in binary string format.

`ristrettoscalarreduce(BINARY(32) a)`

The function reduces `a` to `a mod L` and returns the resulting integer in binary string format.

`ristrettoscalarinvert(BINARY(32) a)`

The function computes the multiplicative inverse of `a over L` and returns the result in binary string format.

`ristrettoscalarnegate(BINARY(32) a)`

The function returns `neg` so that `a + neg = 0 (mod L)`.

`ristrettoscalarcomplement(BINARY(32) a)`

The function returns `comp` so that `a + comp = 1 (mod L)`.

`ristrettoscalaradd(BINARY(32) a, BINARY(32) b)`

The function returns the result of `a + b (mod L)`.

`ristrettoscalarsub(BINARY(32) a, BINARY(32) b)`

The function returns the result of `a - b (mod L)`.

`ristrettoscalarmul(BINARY(32) a, BINARY(32) b)`

The function retuns the result of `a * b (mod L)`.

== Development

Compiling this project requires at least the following packages to be installed:

- `make`
- `automake`
- `autoconf`
- `libtool`
- `mariadb-devel`
- `libsodium-devel`

To install, run the following commands in project root directory:
[source,shell]
----
autoreconf -fvi

./configure
make
sudo make install
sudo make installdb
----
And to uninstall, run the following commands:
[source,shell]
----
make uninstalldb
make uninstall
----

== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/repo-template/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
